apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "azure-advanced-backup.fullname" . }}
  labels:
    {{- include "azure-advanced-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.config.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: PG_DATABASES
                  value: {{ .Values.config.postgres.databases }}
                - name: PG_USE_CUSTOM_FORMAT
                  value: "{{ .Values.config.postgres.useCustomFormat }}"
                - name: PG_ADD_OPTIONS
                  value: "{{ .Values.config.postgres.additionalOptions }}"
                - name: AZ_APPLICATION_ID
                  value: {{ .Values.config.auth.applicationId }}
                - name: AZCOPY_SPA_CLIENT_SECRET
                  value: {{ .Values.config.auth.secret }}
                - name: AZ_TENANT_ID
                  value: {{ .Values.config.auth.tenantId }}
                - name: BACKUP_STORAGE_ACCOUNT
                  value: {{ .Values.config.backupStorage.account }}
                - name: BACKUP_STORAGE_CONTAINER
                  value: {{ .Values.config.backupStorage.container }}
                - name: CONTAINERS
                  value: {{ .Values.config.containers }}
                - name: MANAGED_DISKS
                  value: {{ .Values.config.managedDisks }}
                - name: "DEBUG"
                  value: "{{.Values.config.debug}}"
                - name: "RESOURCE_GROUP_LOCK_ID"
                  value: "{{ .Values.config.resourceGroupLockId }}"
                - name: "COPY_SNAPSHOTS"
                  value: "{{ .Values.config.copySnapshots }}"
                - name: "SNAPSHOT_RETENTION_DAYS"
                  value: "{{ .Values.config.snapshotRetentionDays }}"
          restartPolicy: OnFailure
