# Default values for azure-advanced-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/dodevops/azure-advanced-backup
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

config:
  auth:
    # -- The id of the application to authenticate with
    applicationId: ""
    # -- The secret of the application
    secret: ""
    # -- Azure tenant id
    tenantId: ""

  postgres:
    # -- Whitespace separated list of database logins in the form
    #    `BACKUP_NAME:USERNAME:PASSWORD:HOST:DATABASE_NAME`
    databases: ""
    # -- set to yes to use the pg_dump custom format (`--format c`) and a dmp suffix instead of the sql format and an
    #    sql suffix
    useCustomFormat: "no"
    #
    # -- optional additional pg_dump parameters, e.g. to support --no-acl --no-ower in dump which may cause problems together with the azure flexible server
    additionalOptions: ""

  backupStorage:
    # -- Name of the storage account to sync the containers to
    account: ""
    # -- Name of the storage container to sync the container contents to
    container: ""
  # -- Whitespace separated list of storage containers  in the form
  #    `BACKUP_NAME:STORAGE_ACCOUNT_NAME:CONTAINER_NAME`
  containers: ""
  # -- Whitespace separated list of managed disks in the form
  #    `DISK_NAME:DISK_URI:RESOURCEGROUP_NAME`
  managedDisks: ""
  # -- Cronjob schedule
  schedule: "0 0 * * *"
  # -- Set to "yes" to enable debug output. **WARNING** This will potentially output sensitive information
  #    to the log!
  debug: "no"
  # -- Set to the id of a resource group lock to remove when deleting snapshots and recreate it afterwards
  resourceGroupLockId: ""
  # -- If set to "true", copies the managed disk snapshots as a single VHD into the backup storage account. The
  #    existing VHD will be overwritten. If not set to "true", the snapshots will stay where they
  #    were created and get deleted after the days given in snapshotRetentionDays.
  copySnapshots: "true"
  # -- Number of days to keep a snapshot. Note that this only applies if copySnapshots is set to false.
  snapshotRetentionDays: 7
